### ISSUE TITLE
Valid config file could not be found when config transform files are present

### ISSUE THREAD

**Issue by chrisdevita** [mthamil/EFDocumentationGenerator#12]
For web applications a valid config file could not be found.  After a bit of investigating I found that this happens when there are config transform files associated with the Web.config file (Web.Debug.config and Web.Release.config).

**Comment by mthamil** [comment]
Thanks for the report. Just out of curiosity, which config is your connection string information in? Or is it in multiple?

**Comment by chrisdevita** [comment]
Its in web.config. I was just testing using the default web application project template that visual studio provides. When I deleted the extra config files the document generator worked.

**Comment by chrisdevita** [comment]
Its in web.config. I was just testing using the default web application project template that visual studio provides. When I deleted the extra config files the document generator worked.

**Comment by mthamil** [comment]
Alright, thanks. It may be a regression because I thought at one point it worked.

**Comment by mthamil** [comment]
This is fixed in [v2.1.1](https://github.com/mthamil/EFDocumentationGenerator/releases/tag/v2.1.1).
