### ISSUE TITLE
Missing documentation piece regarding T4 template modification

### ISSUE THREAD

**Issue by Torgrimm** [mthamil/EFDocumentationGenerator#14]
In the description for the project, there is this statement:

> To make use of this extra information, the template (.tt) file that generates the entities will require modifications.

It would be great, if there would be any documentation, about the necessary modifications with an example.

**Comment by mthamil** [comment]
That's a good suggestion, thanks.

On Aug 21, 2017 3:10 AM, Torgrimm <notifications@github.com> wrote:

In the description for the project, there is this statement:

To make use of this extra information, the template (.tt) file that generates the entities will require modifications.

It would be great, if there would be any documentation, about the necessary modifications with an example.

**Comment by mthamil** [comment]
I have added [documentation ](https://github.com/mthamil/EFDocumentationGenerator/wiki/Template-Modification) to the Wiki and added a link to it from the extension page.
