### ISSUE TITLE
Does not support renamed fields

### ISSUE THREAD

**Issue by JimmyRascon** [mthamil/EFDocumentationGenerator#18]
I use uppercase names with underscores in my database and Pascal Case names in the edmx file.
When the field's name in the edmx file does not match the column's name in the database, it does not copy the MS_Description.

Example:
(_column name_) -> (_field name_)

TITULO -> Titulo -> **WORKS**
TITULO -> Prueba -> **DOES NOT WORK**
FECHA_INICIO -> FechaInicio -> **DOES NOT WORK**

**Comment by mthamil** [comment]
Thanks for your feedback. Would you happen to have an example edmx available? The extension uses the edmx to map between database names and entity names, in particular the EntitySetMapping sections.

**Comment by JimmyRascon** [comment]
Hi, the extension works well mapping database names and entity names, but does not work for column names

Here is an example:
[TestEdmx.zip](https://github.com/mthamil/EFDocumentationGenerator/files/2061465/TestEdmx.zip)

```xml
<EntitySetMapping Name="TEST_PRODUCTS">
  <EntityTypeMapping TypeName="TestModel.Products">
    <MappingFragment StoreEntitySet="TEST_PRODUCTS">
      <ScalarProperty Name="Id" ColumnName="PRODUCT_ID" />
      <ScalarProperty Name="Name" ColumnName="NAME" />
      <ScalarProperty Name="Description" ColumnName="DESCRIPTION" />
      <ScalarProperty Name="AlternativeName" ColumnName="ALT_NAME" />
      <ScalarProperty Name="ShippingCost" ColumnName="SHIPPING_COST" />
    </MappingFragment>
  </EntityTypeMapping>
</EntitySetMapping>
```

For example, it doesn't find a description in the database for "AlternativeName", because the column name is "ALT_NAME".

**Comment by mthamil** [comment]
Ohhh ok. That seems fairly simple to fix. I will try to get this done over the weekend. Thanks for your help.

**Comment by JimmyRascon** [comment]
It works nice now, thanks!

**Comment by mthamil** [comment]
Great to hear!
