### ISSUE TITLE
Not yet compatible with VS2015/VS2017

### ISSUE THREAD

**Issue by uzinakod** [mthamil/EFDocumentationGenerator#3]
Hi,

Is there any plan to make the extension available for VS2015/VS2017 ?

Thanks

**Comment by mthamil** [comment]
I can certainly look into it. What version of Entity Framework are you using?

On May 15, 2017 6:55 AM, uzinakod <notifications@github.com> wrote:

Hi,

Is there any plan to make the extension available for VS2015/VS2017 ?

Thanks

**Comment by uzinakod** [comment]
I am using EF6.
In a very lazy way I've tried to just update the target versions of VS and
rebuild but there has to be other changes that are needed in order for it
to work.

Thank you very much for looking into it :)

*S**ébastien Daupleix *| Fondateur
+1 514.825.2511
https://www.linkedin.com/in/sdaupleix

**Comment by mthamil** [comment]
The extension should now be compatible with 2017. I am still looking into multi-targeting for 2015.

**Comment by uzinakod** [comment]
awesome thank you !!
I'll soon be able to give it a try

*S**ébastien Daupleix *
